2016-05-12 21:38:34,122 [Thread-2:10056] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 43, in index
    return render(request, 'index.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "D:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\Python27\lib\site-packages\django\template\context.py", line 256, in bind_template
    processors = (template.engine.template_context_processors +
  File "D:\Python27\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 105, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 105, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "D:\Python27\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named blog.views
2016-05-12 21:39:14,628 [Thread-2:2332] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 43, in index
    return render(request, 'index.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "D:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\Python27\lib\site-packages\django\template\context.py", line 256, in bind_template
    processors = (template.engine.template_context_processors +
  File "D:\Python27\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 105, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 105, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "D:\Python27\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "D:\Python27\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "OnlineLibraryApp.views" does not define a "global_settings" attribute/class
2016-05-12 21:39:45,854 [Thread-2:9872] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 43, in index
    return render(request, 'index.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "D:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\Python27\lib\site-packages\django\template\context.py", line 260, in bind_template
    updates.update(processor(self.request))
ValueError: dictionary update sequence element #0 has length 8; 2 is required
2016-05-12 21:49:33,809 [Thread-35:11176] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/OnlineLibraryApp/comment/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1496, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1245, in response_action
    response = func(self, request, queryset)
  File "D:\Python27\lib\site-packages\django\contrib\admin\actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "D:\Python27\lib\site-packages\django\contrib\admin\utils.py", line 163, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "D:\Python27\lib\site-packages\django\contrib\admin\utils.py", line 223, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "D:\Python27\lib\site-packages\django\contrib\admin\utils.py", line 209, in _nested
    ret = [format_callback(obj)]
  File "D:\Python27\lib\site-packages\django\contrib\admin\utils.py", line 136, in format_callback
    force_text(obj))
  File "D:\Python27\lib\site-packages\django\utils\encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\models.py", line 81, in __unicode__
    return self.book.name
  File "D:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 169, in __get__
    rel_obj = qs.get()
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Book matching query does not exist.
2016-05-12 23:54:21,878 [Thread-14:6104] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist.html
2016-05-12 23:54:56,946 [Thread-15:10824] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist.html
2016-05-12 23:59:08,851 [Thread-2:10972] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist.html
2016-05-13 00:17:03,809 [Thread-2:10552] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 70, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 167, in render
    values = list(values)
TypeError: 'Manager' object is not iterable
2016-05-13 00:19:46,829 [Thread-60:10312] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 70, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 167, in render
    values = list(values)
TypeError: 'Manager' object is not iterable
2016-05-13 00:19:59,869 [Thread-62:11160] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 70, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 167, in render
    values = list(values)
TypeError: 'Manager' object is not iterable
2016-05-13 00:21:59,174 [Thread-2:10600] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 46, in index
    index_bookList = Book.objects[:12]
TypeError: 'Manager' object has no attribute '__getitem__'
2016-05-13 00:26:01,101 [Thread-2:11228] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 44, in index
    index_bookList = Book.objects[:12]
TypeError: 'Manager' object has no attribute '__getitem__'
2016-05-13 00:26:02,414 [Thread-3:6104] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 44, in index
    index_bookList = Book.objects[:12]
TypeError: 'Manager' object has no attribute '__getitem__'
2016-05-13 01:30:19,013 [Thread-15:10540] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist/category
2016-05-13 01:35:58,035 [Thread-61:12188] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist/category
2016-05-13 01:36:04,177 [Thread-72:11936] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist/index/category
2016-05-13 01:36:06,233 [Thread-73:11964] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist/index/category
2016-05-13 02:16:52,266 [Thread-69:12084] [django.request:182] [base:get_response] [WARNING]- Not Found: /category/index/category
2016-05-13 02:16:56,882 [Thread-70:9832] [django.request:182] [base:get_response] [WARNING]- Not Found: /category/index/category
2016-05-13 02:17:00,654 [Thread-81:11564] [django.request:182] [base:get_response] [WARNING]- Not Found: /category/.category
2016-05-13 02:19:45,634 [Thread-133:11488] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist/category
2016-05-13 02:20:10,776 [Thread-155:9348] [django.request:182] [base:get_response] [WARNING]- Not Found: /booklist/category
2016-05-13 03:08:32,082 [Thread-27:2548] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "D:\Python27\lib\site-packages\django\template\defaultfilters.py", line 615, in slice_filter
    for x in arg.split(':'):
AttributeError: 'int' object has no attribute 'split'
2016-05-13 03:15:15,233 [Thread-68:13272] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '(book.name)' from 'len(book.name)'
2016-05-13 03:26:34,621 [Thread-92:11896] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'mySlice'
2016-05-13 03:26:40,608 [Thread-93:13112] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'mySlice'
2016-05-13 03:26:41,963 [Thread-94:9276] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'mySlice'
2016-05-13 03:28:00,881 [Thread-96:12028] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'mySlice'
2016-05-13 03:29:19,213 [Thread-98:12112] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'mySlice'
2016-05-13 03:29:20,983 [Thread-99:12924] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'mySlice'
2016-05-13 03:32:24,786 [Thread-101:9432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'mySlice' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:32:28,927 [Thread-102:12744] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'mySlice' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:32:45,229 [Thread-104:10852] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'mySlice' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:32:46,746 [Thread-105:11912] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'mySlice' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:33:51,596 [Thread-107:3348] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:33:52,671 [Thread-108:12948] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:33:53,375 [Thread-109:12332] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:33:54,983 [Thread-110:12488] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:38:04,848 [Thread-112:12704] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:39:25,028 [Thread-114:11696] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:40:09,571 [Thread-116:8140] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'percent' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:40:10,992 [Thread-117:11516] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'percent' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 03:40:13,278 [Thread-118:12860] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /booklist/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 61, in booklist
    return render(request, 'booklist.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'percent' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2016-05-13 05:02:33,588 [Thread-26:12096] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/Css/style.css
2016-05-13 05:02:33,631 [Thread-32:12628] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:02:33,808 [Thread-40:12636] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:03:13,586 [Thread-42:13216] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/Css/style.css
2016-05-13 05:03:13,621 [Thread-48:4364] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:03:13,829 [Thread-53:12492] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:05:37,841 [Thread-61:12220] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:05:38,085 [Thread-68:12832] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:10:48,278 [Thread-87:11412] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:10:58,961 [Thread-99:12136] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:14:21,681 [Thread-113:12544] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:16:17,622 [Thread-127:3980] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:16:17,904 [Thread-139:11476] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:16:45,496 [Thread-147:11332] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:16:45,749 [Thread-159:13032] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:18:00,831 [Thread-167:11544] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:18:01,065 [Thread-179:12156] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:21:35,466 [Thread-198:11400] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/OnlineLibraryApp/bookcategory/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1382, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 714, in log_addition
    object_repr=force_text(object),
  File "D:\Python27\lib\site-packages\django\utils\encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\models.py", line 71, in __unicode__
    return self.name
AttributeError: 'BookCategory' object has no attribute 'name'
2016-05-13 05:22:11,101 [Thread-200:12784] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/OnlineLibraryApp/bookcategory/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1382, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 714, in log_addition
    object_repr=force_text(object),
  File "D:\Python27\lib\site-packages\django\utils\encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\models.py", line 71, in __unicode__
    return self.name
AttributeError: 'BookCategory' object has no attribute 'name'
2016-05-13 05:25:14,293 [Thread-29:11756] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/images/si.jpg
2016-05-13 05:35:34,461 [Thread-205:11896] [django.request:182] [base:get_response] [WARNING]- Not Found: /detail/single.html
2016-05-13 08:11:40,834 [Thread-8:8240] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-13 09:11:16,003 [Thread-2:6808] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /detail/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 104, in detail
    'book': id} if request.user.is_authenticated() else{'book': id})
  File "D:\Python27\lib\site-packages\django\utils\functional.py", line 205, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'url'
2016-05-13 09:21:38,290 [Thread-18:7948] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /detail/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 105, in detail
    return render(request, 'detail.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'comment_post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 09:24:40,898 [Thread-2:8964] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /detail/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 105, in detail
    return render(request, 'detail.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'comment_post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 09:29:00,187 [Thread-3:7464] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /detail/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 105, in detail
    return render(request, 'detail.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'comment_post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 11:12:57,341 [Thread-26:8476] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /detail/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 116, in detail
    return render(request, 'detail.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'do_logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 11:15:18,234 [Thread-2:6684] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 63, in index
    return render(request, 'index.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'do_logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 11:15:57,562 [Thread-2:3212] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 63, in index
    return render(request, 'index.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'do_logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 11:15:58,933 [Thread-3:4284] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 63, in index
    return render(request, 'index.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'do_logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-05-13 11:25:46,823 [Thread-4:7732] [django.request:182] [base:get_response] [WARNING]- Not Found: /search_page
2016-05-13 11:26:40,470 [Thread-6:4224] [django.request:182] [base:get_response] [WARNING]- Not Found: /search_page
2016-05-13 18:30:27,469 [Thread-8:9684] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-13 18:41:53,039 [Thread-2:3576] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /reg/
2016-05-14 16:15:55,134 [Thread-21:5084] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 16:16:53,026 [Thread-41:3144] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 16:22:03,809 [Thread-82:3244] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 17:43:23,020 [Thread-19:9116] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 20:51:53,875 [Thread-67:11228] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 22:04:13,484 [Thread-6:8984] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 22:11:38,038 [Thread-45:6432] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 22:11:38,302 [Thread-46:3872] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-14 23:03:35,227 [Thread-249:5724] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-15 17:21:49,828 [Thread-21:1076] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-16 18:00:44,171 [Thread-21:9668] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-18 23:56:21,098 [Thread-19:7528] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-19 00:26:28,338 [Thread-17:9964] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-19 00:27:46,068 [Thread-37:3468] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-19 00:27:46,306 [Thread-38:3820] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-05-19 00:29:20,321 [Thread-56:8836] [django.request:182] [base:get_response] [WARNING]- Not Found: /category/admin
2016-05-19 01:31:03,621 [Thread-29:8636] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/OnlineLibraryApp/bookmark/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1382, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\Python27\lib\site-packages\django\contrib\admin\options.py", line 714, in log_addition
    object_repr=force_text(object),
  File "D:\Python27\lib\site-packages\django\utils\encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\models.py", line 61, in __unicode__
    return self.name
AttributeError: 'BookMark' object has no attribute 'name'
2016-05-19 04:12:10,130 [Thread-2:2692] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /detail/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\workspace\OnlineLibrary\src\OnlineLibraryApp\views.py", line 162, in detail
    return render(request, 'detail.html', locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 27: 'elseif', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
